hmrc/income-tax-submission-frontend

test/views/OverviewPageViewSpec.scala

Changed to lower case c in unit tests

SASS-28b : unit test fix

---

app/common/SessionValues.scala
app/config/FrontendAppConfig.scala
app/controllers/OverviewPageController.scala
app/models/DividendsModel.scala
app/models/IncomeSourcesModel.scala
app/views/OverviewPageView.scala.html
it/connectors/IncomeSourcesConnectorSpec.scala
test/controllers/OverviewPageControllerSpec.scala
test/models/DividendsModelSpec.scala
test/models/IncomeSourcesModelSpec.scala
test/views/OverviewPageViewSpec.scala

[Link to the epic](https://jira.tools.tax.service.gov.uk/browse/SASS-36)

Sass 88 Updated income logic

---

app/controllers/predicates/AuthorisedAction.scala
it/controllers/StartPageControllerTest.scala
it/helpers/WireMockHelper.scala
it/utils/IntegrationTest.scala
it/utils/MockAuthConnector.scala
test/views/OverviewPageViewSpec.scala

[DM] [SASS-183] Added confidence level 200 as a requirement

---

app/common/EnrolmentCommon.scala
app/controllers/OverviewPageController.scala
app/controllers/predicates/AuthorisedAction.scala
app/models/User.scala
it/controllers/StartPageControllerTest.scala
test/controllers/OverviewPageControllerSpec.scala
test/controllers/StartPageControllerSpec.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/utils/UnitTest.scala

Reverts hmrc/income-tax-submission-frontend#38

Revert "SASS-236-1 - Pulled nino from enrolments rather than in session"

---

app/views/errors/InternalServerErrorPage.scala.html
app/views/errors/NotFoundPage.scala.html
app/views/errors/ServiceUnavailablePage.scala.html
test/views/errors/InternalServerErrorPageSpec.scala
test/views/errors/NotFoundPageSpec.scala
test/views/errors/ServiceUnavailableErrorPageSpec.scala

Updated markup for error pages after demo comments. 
@dnyuar could you check with Barry when you demo your story to see if you need to make these same changes

Sass 291 markup

---

test/utils/ViewTest.scala
test/views/StartPageViewSpec.scala

The implementation for this test was done as part of [SASS-271](https://github.com/hmrc/income-tax-submission-frontend/pull/62)
Tests were added in this PR

SASS-341 Added role for button to tests

---

app/controllers/predicates/AuthorisedAction.scala

Line 134 contained "logger.warn" which has also been changed to info, please confirm if correct

SASS-413 changed logger debugs to info's

---

app/config/AppConfig.scala
app/controllers/OverviewPageController.scala
app/controllers/StartPageController.scala
app/controllers/TaxYearErrorController.scala
app/controllers/predicates/TaxYearAction.scala
app/views/errors/WrongTaxYearPage.scala.html
conf/app.routes
conf/application.conf
conf/messages
it/controllers/OverviewPageControllerTest.scala
it/controllers/StartPageControllerTest.scala
test/config/MockAppConfig.scala
test/controllers/OverviewPageControllerSpec.scala
test/controllers/StartPageControllerSpec.scala
test/controllers/TaxYearErrorControllerSpec.scala
test/controllers/predicates/TaxYearActionSpec.scala
test/views/errors/WrongTaxYearPageSpec.scala

Sass 430 2

---

test/utils/ViewTest.scala

I accidentally merged code with an error, this is a fix to that.

Fix for pipeline

---

app/config/AppConfig.scala
test/views/OverviewPageViewSpec.scala
test/views/StartPageViewSpec.scala

SASS-491 - fixed the view and change agent url to contain /client-utr

---

app/models/GiftAidModel.scala
app/models/GiftAidPaymentsModel.scala
app/models/GiftsModel.scala
app/models/IncomeSourcesModel.scala
it/connectors/IncomeSourcesConnectorSpec.scala
test/models/GiftAidModelSpec.scala

[[SASS-571]](https://jira.tools.tax.service.gov.uk/browse/SASS-571)

[SASS-571] Handling of gift aid data by income-tax-submission-frontend

---

app/audit/EnterUpdateAndSubmissionServiceDetail.scala
app/controllers/StartPageController.scala
app/views/StartPage.scala.html
conf/app.routes
it/controllers/StartPageControllerTest.scala
project/plugins.sbt
test/controllers/IVFailureControllerSpec.scala
test/controllers/IVUpliftControllerSpec.scala
test/controllers/StartPageControllerSpec.scala
test/models/EnterUpdateAndSubmissionServiceDetailSpec.scala
test/utils/UnitTest.scala
test/utils/ViewTest.scala
test/views/StartPageViewSpec.scala

[DM] [SASS-601] Added connector for submit gift-aid

---

app/audit/EnterUpdateAndSubmissionServiceAuditDetail.scala
app/controllers/OverviewPageController.scala
app/controllers/StartPageController.scala
it/controllers/StartPageControllerTest.scala
test/audit/EnterUpdateAndSubmissionServiceAuditDetailSpec.scala
test/controllers/IVFailureControllerSpec.scala
test/controllers/IVUpliftControllerSpec.scala
test/controllers/StartPageControllerSpec.scala
test/utils/UnitTest.scala
test/views/YouNeedAgentServicesViewSpec.scala

[SASS-651](https://jira.tools.tax.service.gov.uk/browse/SASS-651)

SASS-651 : Added User Nino to Service Entry Audit Event

---

app/config/AppConfig.scala
app/controllers/IVFailureController.scala
app/controllers/SignOutController.scala
app/views/headerFooterTemplate/BeforeBodyContent.scala.html
app/views/headerFooterTemplate/Layout.scala.html
app/views/templates/helpers/BetaBar.scala.html
conf/app.routes
it/controllers/OverviewPageControllerTest.scala
it/helpers/WireMockHelper.scala
test/config/AppConfigSpec.scala
test/config/MockAppConfig.scala
test/controllers/SignOutControllerSpec.scala
test/views/IVFailurePageSpec.scala
test/views/helpers/BetaBarViewSpec.scala

[SASS-638] https://jira.tools.tax.service.gov.uk/browse/SASS-607

[Sass 638] - Differentiate URL redirect link by actor

---

app/views/OverviewPageView.scala.html
test/views/OverviewPageViewSpec.scala

Edited direct children of ol/ul elements from spans to p tags
[SASS-347](https://jira.tools.tax.service.gov.uk/browse/SASS-347)

SASS-347 changed spans to p tags

---

app/controllers/errors/AgentAuthErrorController.scala
app/controllers/predicates/AuthorisedAction.scala
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/errors/AgentAuthErrorControllerISpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/ViewHelpers.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/views/AgentAuthErrorPageViewSpec.scala

SASS-707 page created for error url matches

---

app/controllers/OverviewPageController.scala
app/controllers/StartPageController.scala
app/controllers/predicates/TaxYearAction.scala
app/models/employment/AllEmploymentData.scala
app/models/employment/Benefits.scala
app/models/employment/EmploymentBenefits.scala
app/models/employment/EmploymentData.scala
app/models/employment/EmploymentExpenses.scala
app/models/employment/Expenses.scala
app/models/employment/Pay.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/controllers/OverviewPageControllerTest.scala

Added employment model to session
https://jira.tools.tax.service.gov.uk/browse/SASS-730

added employment to session from submission call

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/config/MockAppConfig.scala
test/views/OverviewPageViewSpec.scala

Added employment line to the overview page
https://jira.tools.tax.service.gov.uk/browse/SASS-669

SASS-669: Added employment line to the overview page

---

app/controllers/IVFailureController.scala
app/controllers/predicates/AuthorisedAction.scala
app/controllers/predicates/TaxYearAction.scala
app/filters/SessionIdFilter.scala
it/controllers/errors/AgentAuthErrorControllerISpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/ViewHelpers.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/config/MessagesSpec.scala
test/connectors/httpParsers/APIParserSpec.scala
test/controllers/IVFailureControllerSpec.scala
test/controllers/IVUpliftControllerSpec.scala
test/controllers/SessionExpiredControllerSpec.scala
test/controllers/SignOutControllerSpec.scala
test/controllers/predicates/TaxYearActionSpec.scala
test/models/APIErrorBodyModelSpec.scala
test/utils/UnitTest.scala

SASS-682 completed dependancies

---

app/views/authErrorPages/AgentAuthErrorPageView.scala.html
conf/messages
conf/messages.cy
it/controllers/errors/AgentAuthErrorControllerISpec.scala
it/itUtils/ViewHelpers.scala
test/utils/ViewTest.scala
test/views/AgentAuthErrorPageViewSpec.scala
test/views/IVFailurePageSpec.scala
test/views/OverviewPageViewSpec.scala
test/views/StartPageViewSpec.scala
test/views/errors/IndividualUnauthorisedViewSpec.scala
test/views/errors/InternalServerErrorPageSpec.scala
test/views/errors/NotFoundPageSpec.scala
test/views/errors/ServiceUnavailableErrorPageSpec.scala
test/views/errors/TimeoutPageSpec.scala
test/views/errors/WrongTaxYearPageSpec.scala

SASS-872 - Added client-utr link to agent authorisation error page

---

app/models/employment/Pay.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/ViewHelpers.scala
test/utils/UnitTest.scala

update pay model
[SASS-884](https://jira.tools.tax.service.gov.uk/browse/SASS-864)

update pay model

---

app/views/OverviewPageView.scala.html
conf/messages
conf/messages.cy
test/views/OverviewPageViewSpec.scala

Changes requested to the 1st bullet point header and paragraph below to match document
https://docs.google.com/document/d/1oMyILuQVo-HIM3YZ1NaOjhM2vakRDGo7-0S27rMQp6U/edit?ts=6076a4f9#

overview page changes

---

app/config/AppConfig.scala
test/views/OverviewPageViewSpec.scala

PR to change the Personal FE url for the interest check your answers page to match what is now in Personal FE
[SASS-833](https://jira.tools.tax.service.gov.uk/browse/SASS-493)

[SASS-833a] - refactor CYA url for Personal FE in appConfig

---

app/models/employment/EmploymentData.scala
app/models/employment/Pay.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/itUtils/IntegrationTest.scala
test/utils/UnitTest.scala

updated the Pay model in EmploymentData to align with the latest DES Spec (2.0.0)
[SASS-897](https://jira.tools.tax.service.gov.uk/browse/SASS-897)

[SASS-897] Update Pay model to align with the latest DES Spec

---

app/connectors/httpParsers/CalculationIdHttpParser.scala
app/utils/PagerDutyHelper.scala

updated pager log name
https://jira.tools.tax.service.gov.uk/browse/SASS-779

updated pager log name

---

app/views/OverviewPageView.scala.html
it/controllers/OverviewPageControllerTest.scala
project/AppDependencies.scala
test/views/OverviewPageViewSpec.scala

[SASS-945](https://jira.tools.tax.service.gov.uk/browse/SASS-945)
the current pull request?
the current pull request?

[SASS-945] Axe issue fix

---

app/connectors/httpParsers/CalculationIdHttpParser.scala
app/utils/PagerDutyHelper.scala
it/connectors/CalculationIdConnectorSpec.scala
project/AppDependencies.scala
test/config/MessagesSpec.scala

[SASS-900](https://jira.tools.tax.service.gov.uk/browse/SASS-900)
the current pull request?
the current pull request?

[SASS-900] added connector 422/UNPROCESSSABLE ENTITY

---

app/config/AppConfig.scala
app/controllers/UnauthorisedUserErrorController.scala
app/controllers/errors/ReturnTaxYearExistsController.scala
app/views/errors/IVFailurePage.scala.html
app/views/errors/ReturnTaxYearExistsView.scala.html
app/views/headerFooterTemplate/BeforeBodyContent.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/errors/ReturnTaxYearExistsControllerISpec.scala

Creation of error page view to be used with a conflict api result when it comes to wiring up the crystallisation journey
[SASS-1060](https://jira.tools.tax.service.gov.uk/browse/SASS-1060)

SASS-1060 : "We already have an Income Tax Return for that tax year" page

---

app/controllers/errors/TaxReturnPreviouslyUpdatedController.scala
app/views/errors/TaxReturnPreviouslyUpdatedView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/errors/ReturnTaxYearExistsControllerISpec.scala
it/controllers/errors/TaxReturnPreviouslyUpdatedControllerISpec.scala

Created Previously updated income Tax Return Page
[SASS-1062](https://jira.tools.tax.service.gov.uk/browse/SASS-1062)

SASS-1062 : Income tax return has been updated page & logic

---

app/controllers/errors/OtherTryingToSubmitController.scala
app/views/errors/AddressHasChangedPage.scala.html
app/views/errors/OtherTryingToSubmitView.scala.html
app/views/errors/ReturnTaxYearExistsView.scala.html
app/views/errors/TaxReturnPreviouslyUpdatedView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/errors/OtherTryingToSubmitControllerISpec.scala

Added Some else is trying to submit page and appropriate tests
[SASS-1063](https://jira.tools.tax.service.gov.uk/browse/SASS-1063)

SASS-1063 : Some else is trying to submit page

---

app/connectors/DeclareCrystallisationConnector.scala
app/connectors/httpParsers/DeclareCrystallisationHttpParser.scala
app/services/DeclareCrystallisationService.scala
build.sbt
it/connectors/CalculationIdConnectorSpec.scala
it/connectors/DeclareCrystallisationConnectorSpec.scala
project/AppDependencies.scala
test/services/DeclareCrystallisationServiceSpec.scala

DeclareCrystallisationConnector Frontend connector
[SASS-1147](https://jira.tools.tax.service.gov.uk/browse/SASS-1147)

[SASS-1147] DeclareCrystallisationConnector

---

app/models/employment/Pay.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/itUtils/IntegrationTest.scala
test/utils/UnitTest.scala

This is removing tips and other payments from the pay model. The subtask for this ticket is SASS-1159
[SASS-1126](https://jira.tools.tax.service.gov.uk/browse/SASS-1126)

Removed pay from model

---

conf/application.conf

Change so EOY journey tests can be run locally
https://jira.tools.tax.service.gov.uk/browse/SASS-1143

set taxYear error switch to false

---

conf/application.conf

Setting taxYearErrorFeatureSwitch back to false

setting tax year feature switch back to false

---

app/views/OverviewPageView.scala.html
conf/messages
conf/messages.cy
it/controllers/OverviewPageControllerISpec.scala

Content changes for crystallisation version of the overview page.
[SASS-1227](https://jira.tools.tax.service.gov.uk/browse/SASS-1227)

SASS-1261 - Overview Page for crystallisation content changes

---

app/views/TaxReturnReceivedView.scala.html

[SASS-1228](https://jira.tools.tax.service.gov.uk/browse/SASS-1228)

display all dates inline

---

app/audit/FinalDeclarationDetail.scala
app/audit/IntentToCrystalliseDetail.scala
app/controllers/DeclarationPageController.scala
app/controllers/OverviewPageController.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/OverviewPageControllerISpec.scala
it/helpers/WireMockHelper.scala
test/controllers/OverviewPageControllerSpec.scala

Added in audit events for both the intent to crystallise and the final declaration.
[SASS-1048](https://jira.tools.tax.service.gov.uk/browse/SASS-1048)
[SASS-1049](https://jira.tools.tax.service.gov.uk/browse/SASS-1049)

[DM] [SASS-1272] Intent to & Final crystallisation audit events added

---

app/config/AppConfig.scala
app/views/TaxReturnReceivedView.scala.html
project/AppDependencies.scala

Url Update to align with the new View and Change page changes (to be merged after they have been)
[SASS-1229](https://jira.tools.tax.service.gov.uk/browse/SASS-1229)

SASS-1229 : Frontend changes for final calc page

---

app/config/AppConfig.scala
app/controllers/OverviewPageController.scala
conf/app.routes
project/AppDependencies.scala
test/controllers/OverviewPageControllerSpec.scala

Adding agent view estimation route to appConfig and overview page

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/connectors/NrsConnector.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/controllers/DeclarationPageController.scala
app/models/NrsSubmissionModel.scala
app/services/NrsService.scala
conf/application.conf
it/connectors/NrsConnectorSpec.scala
it/controllers/DeclarationPageControllerISpec.scala
it/helpers/WireMockHelper.scala
it/itUtils/IntegrationTest.scala
test/models/NrsSubmissionModelSpec.scala
test/services/NrsServiceSpec.scala

Connecting income-tax-submission FE with income-tax-nrs-proxy MS
API Spec - https://confluence.tools.tax.service.gov.uk/display/NR/Submission+API+Specification+1.2
[SASS-178](https://jira.tools.tax.service.gov.uk/browse/SASS-178)

Sass 178 - Connect income tax submission FE MS with proxy NRS MS

---

app/assets/stylesheets/application.scss
app/config/AppConfig.scala
app/views/headerFooterTemplate/Head.scala.html
conf/application.conf
conf/prod.routes
conf/testOnlyDoNotUseInAppConf.routes
it/config/ErrorHandlerISpec.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/IVUpliftControllerISpec.scala
it/controllers/OverviewPageControllerISpec.scala
it/controllers/SessionExpiredControllerISpec.scala
it/controllers/StartPageControllerISpec.scala
it/controllers/TaxReturnReceivedControllerISpec.scala
it/controllers/errors/AddressHasChangedPageControllerISpec.scala
it/controllers/errors/AgentAuthErrorControllerISpec.scala
it/controllers/errors/BusinessValidationRulesControllerISpec.scala
it/controllers/errors/IVFailureControllerISpec.scala
it/controllers/errors/IndividualAuthErrorControllerISpec.scala
it/controllers/errors/NoUpdatesProvidedPageControllerISpec.scala
it/controllers/errors/NoValidIncomeSourcesISpec.scala
it/controllers/errors/ReturnTaxYearExistsControllerISpec.scala
it/controllers/errors/TaxReturnPreviouslyUpdatedControllerISpec.scala
it/controllers/errors/TaxYearErrorControllerISpec.scala
it/controllers/errors/UnauthorisedUserErrorControllerISpec.scala
it/controllers/errors/YouNeedAgentServicesControllerISpec.scala
it/controllers/predicates/AuthorisedActionSpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/ViewHelpers.scala
it/itUtils/ViewTest.scala
test/config/MockAppConfig.scala

Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1562](https://jira.tools.tax.service.gov.uk/browse/SASS-1562)

SASS-1562: Update income FE page URLs

---

app/config/AppConfig.scala
app/controllers/DeclarationPageController.scala
conf/application.conf
project/plugins.sbt
test/config/MockAppConfig.scala

Adding feature switch for NRS submission to income-tax-submission-frontend
[SASS-1736](https://jira.tools.tax.service.gov.uk/browse/SASS-1641)

SASS-1736 Adding feature switch for NRS Submission

---

app/connectors/httpParsers/NrsSubmissionHttpParser.scala
it/connectors/NrsConnectorSpec.scala
project/AppDependencies.scala

Changing NrsSubmission httpParser to handle and OK status rather than an accepted status
[SASS-1855](https://jira.tools.tax.service.gov.uk/browse/SASS-1855)

SASS-1855 Handle OK status code instead of Accepted in NrsSubmissionHttpParser

---

app/services/NrsService.scala
app/utils/HMRCHeaderNames.scala
project/AppDependencies.scala
test/services/NrsServiceSpec.scala

Update income FE to specify `User-Agent` and `True-User-Agent` headers for NRS submission.
[SASS-1933](https://jira.tools.tax.service.gov.uk/browse/SASS-1933)

SASS-1933: Update income FE to specify user agent for NRS submission

---

README.md

[SASS-1817](https://jira.tools.tax.service.gov.uk/browse/SASS-1817)

[SASS-1817] update readMe

---

app/config/AppConfig.scala
app/connectors/testOnly/AuthLoginApiConnector.scala
app/controllers/testOnly/UserResearchLoginController.scala
app/forms/testOnly/UserResearchLoginForm.scala
app/models/userResearch/AuthLoginAPIResponse.scala
app/models/userResearch/AuthLoginRequest.scala
app/models/userResearch/DelegatedEnrolment.scala
app/models/userResearch/Enrolment.scala
app/models/userResearch/Identifier.scala
app/models/userResearch/ResearchUser.scala
app/models/userResearch/ResearchUsers.scala
app/views/UserResearchLoginView.scala.html
conf/application.conf
conf/messages
conf/prod.routes
conf/testOnlyDoNotUseInAppConf.routes
it/connectors/testOnly/AuthLoginApiConnectorISpec.scala
it/controllers/testOnly/UserResearchLoginControllerISpec.scala
it/itUtils/IntegrationTest.scala
test/config/MockAppConfig.scala
test/models/userResearch/AuthLoginAPIResponseSpec.scala
test/models/userResearch/AuthLoginRequestSpec.scala
test/models/userResearch/DelegatedEnrolmentSpec.scala
test/models/userResearch/EnrolmentSpec.scala
test/models/userResearch/EnumsSpec.scala
test/models/userResearch/IdentifierSpec.scala
test/models/userResearch/ResearchUserSpec.scala
test/models/userResearch/ResearchUsersSpec.scala

Adding a login page to testOnly as a user research entry point.
[SASS-1674](https://jira.tools.tax.service.gov.uk/browse/SASS-1674)

[DM] [SASS-1674] Added User Research user login page

---

app/controllers/OverviewPageController.scala
app/views/OverviewPageView.scala.html
it/controllers/OverviewPageControllerISpec.scala
project/AppDependencies.scala

[SASS-2043](https://jira.tools.tax.service.gov.uk/browse/SASS-2043)

SASS-2043 - Tax year iteration on ITSASS overview page.

---

app/config/AppConfig.scala
conf/application.conf
test/config/MockAppConfig.scala

CIS feature switch
[SASS-2286](https://jira.tools.tax.service.gov.uk/browse/SASS-2286)

SASS-2286 CIS feature switch

---

app/common/IncomeSources.scala
app/config/AppConfig.scala

added cis to excluded when turned off

---

app/views/OverviewPageView.scala.html

Updated the status tags on the overview pages to use the GovUk tags.
[SASS-2045](https://jira.tools.tax.service.gov.uk/browse/SASS-2045) (parent ticket)

[DM] [SASS-2434] Updated tags to use gokuk tags

---

app/models/employment/AllEmploymentData.scala
build.sbt
it/connectors/IncomeSourcesConnectorSpec.scala
it/itUtils/IntegrationTest.scala
project/build.properties
test/utils/UnitTest.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2388

SASS-2396 Updated employment model

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/connectors/IncomeSourcesConnector.scala
app/controllers/OverviewPageController.scala
app/models/IncomeSourcesModel.scala
app/models/cis/AllCISDeductions.scala
app/models/cis/CISDeductions.scala
app/models/cis/CISSource.scala
app/models/cis/PeriodData.scala
app/models/employment/EmploymentFinancialData.scala
app/models/employment/EmploymentSource.scala
app/models/employment/HmrcEmploymentSource.scala
app/views/OverviewPageView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
it/connectors/IncomeSourcesConnectorSpec.scala
it/controllers/OverviewPageControllerISpec.scala
it/itUtils/IntegrationTest.scala
test/config/MockAppConfig.scala

[SASS-1928](https://jira.tools.tax.service.gov.uk/browse/SASS-1928)

SASS-1928 - Create CIS summary page in year.

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/OverviewPageControllerISpec.scala
test/config/MockAppConfig.scala

[SASS-2211](https://jira.tools.tax.service.gov.uk/browse/SASS-2211)

Inyear tax overview routing

---

app/audit/CreateInYearTaxEstimate.scala
app/controllers/OverviewPageController.scala
app/views/OverviewPageView.scala.html
conf/app.routes
it/controllers/OverviewPageControllerISpec.scala

[SASS-2318](https://jira.tools.tax.service.gov.uk/browse/SASS-2318)

CreateInYearTaxEstimate Audit Event

---

app/assets/stylesheets/itsa-print.css
app/views/headerFooterTemplate/Head.scala.html
app/views/headerFooterTemplate/Layout.scala.html
project/AppDependencies.scala

SASS-2523 fix to print preview styling.
[SASS-2523](https://jira.tools.tax.service.gov.uk/browse/SASS-2523)

SASS-2523 print preview styling

---

app/assets/stylesheets/application.scss
project/AppDependencies.scala

Small change to allow large fonts to return within the gov uk panel (This can be tested in safari by increasing the font size : option cmd +)
[SASS-2525](https://jira.tools.tax.service.gov.uk/browse/SASS-2525)

SASS-2525 : added wrok break css to gov uk panel element

---

project/AppDependencies.scala

Play frontend bumped back down to 3.8.0
[SASS-dependency](ADD URL HERE)

Play frontend downgrade

---

app/views/errors/WrongTaxYearPage.scala.html
conf/messages
conf/messages.cy
it/config/ErrorHandlerISpec.scala
it/connectors/DeclareCrystallisationConnectorSpec.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/connectors/LiabilityCalculationConnectorSpec.scala
it/connectors/NrsConnectorSpec.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/IVUpliftControllerISpec.scala
it/controllers/OverviewPageControllerISpec.scala
it/controllers/StartPageControllerISpec.scala
it/controllers/TaxReturnReceivedControllerISpec.scala
it/controllers/errors/AddressHasChangedPageControllerISpec.scala
it/controllers/errors/BusinessValidationRulesControllerISpec.scala
it/controllers/errors/NoUpdatesProvidedPageControllerISpec.scala
it/controllers/errors/NoValidIncomeSourcesISpec.scala
it/controllers/errors/ReturnTaxYearExistsControllerISpec.scala
it/controllers/errors/TaxReturnPreviouslyUpdatedControllerISpec.scala
it/controllers/errors/TaxYearErrorControllerISpec.scala
it/controllers/testOnly/UserResearchLoginControllerISpec.scala
it/itUtils/IntegrationTest.scala

[SASS-2663](https://jira.tools.tax.service.gov.uk/browse/SASS-2663)

[SASS-2663] intergrationTest dynamic taxYear

---

app/config/AppConfig.scala
app/models/mongo/DatabaseError.scala
app/models/mongo/TailoringUserDataModel.scala
app/models/mongo/TextAndKey.scala
app/models/mongo/UserDataTemplate.scala
app/repositories/RepositoryIndexes.scala
app/repositories/TailoringUserDataRepository.scala
app/repositories/UserDataRepository.scala
app/services/EncryptionService.scala
app/utils/PagerDutyHelper.scala
app/utils/SecureGCMCipher.scala
app/utils/TypeCaster.scala
conf/application.conf
it/itUtils/IntegrationTest.scala
it/repositories/UserDataRepositoryISpec.scala
it/services/EncryptionServiceISpec.scala
test/config/MockAppConfig.scala
test/utils/SecureGCMCipherSpec.scala

[SASS-2618](https://jira.tools.tax.service.gov.uk/browse/SASS-2618)

[SASS-2618] Mongo for tailoring

---

app/config/AppConfig.scala
app/controllers/StartPageController.scala
app/controllers/predicates/InYearAction.scala
app/views/OverviewPageView.scala.html
app/views/StartPageView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
it/connectors/IncomeSourcesConnectorSpec.scala
it/controllers/IVFailureControllerSpec.scala
it/controllers/OverviewPageControllerISpec.scala
it/controllers/StartPageControllerISpec.scala
it/itUtils/IntegrationTest.scala
it/repositories/UserDataRepositoryISpec.scala
test/config/MockAppConfig.scala
test/utils/SecureGCMCipherSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2696

SASS-2776 Updated start page

---

app/views/OverviewPageView.scala.html
app/views/templates/helpers/Breadcrumb.scala.html
conf/messages
conf/messages.cy
it/controllers/OverviewPageControllerISpec.scala
it/controllers/StartPageControllerISpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2696

updated breadcrumb link text

---

app/models/IncomeSourcesModel.scala
app/models/employment/EmploymentData.scala
it/connectors/IncomeSourcesConnectorSpec.scala
it/itUtils/IntegrationTest.scala
test/models/IncomeSourcesModelSpec.scala
test/utils/UnitTest.scala

Align to latest spec for API #1645
[SASS-2803](https://jira.tools.tax.service.gov.uk/browse/SASS-2763)

SASS-2803 Align to latest spec for API #1645

---

app/controllers/AddSectionsToIncomeTaxReturnController.scala
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala

[SASS-2756](https://jira.tools.tax.service.gov.uk/browse/SASS-2756)

Feature-switch add tailoring sections

---

README.md

SASS-2968 Updated README file
[SASS-2935](https://jira.tools.tax.service.gov.uk/browse/SASS-2935)

SASS-2968 updated ReadMe

---

app/controllers/DeclarationPageController.scala
app/controllers/OverviewPageController.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
it/itUtils/OverviewPageHelpers.scala

[SASS-2818](https://jira.tools.tax.service.gov.uk/browse/SASS-2818)

SASS-2818 Add in year action to Income FE to stop pages being accessed in year

---

app/controllers/ExcludeJourneyController.scala
app/controllers/OverviewPageController.scala
app/models/DividendsModel.scala
app/models/ExcludeJourneyModel.scala
app/models/GiftAidPaymentsModel.scala
app/models/GiftsModel.scala
app/models/mongo/ExclusionUserDataModel.scala
app/repositories/ExclusionUserDataRepository.scala
app/services/EncryptionService.scala
app/utils/ShaHashHelper.scala
conf/app.routes
it/controllers/ExcludeJourneyControllerISpec.scala
it/controllers/OverviewExclusionISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala

[SASS-2855](https://jira.tools.tax.service.gov.uk/browse/SASS-2855)

[SASS-2855] add exclusion

---

app/controllers/AddSectionsToIncomeTaxReturnController.scala
app/controllers/OverviewPageController.scala
app/forms/AddSectionsForm.scala
app/views/AddSectionsToIncomeTaxReturnView.scala.html
conf/messages
conf/messages.cy
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
test/forms/AddSectionsFormSpec.scala

Added Pensions checkbox to Tailoring page
[SASS-2916](https://jira.tools.tax.service.gov.uk/browse/SASS-2916)

SASS-2916 : Added Pensions checkbox to Tailoring page

---

app/config/AppConfig.scala
it/controllers/StartPageControllerISpec.scala
it/controllers/TaxReturnReceivedControllerISpec.scala
it/controllers/errors/NoValidIncomeSourcesISpec.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

Update the V&C routes defined in `income-tax-submission-frontend` to match the latest routes.
[SASS-3077](https://jira.tools.tax.service.gov.uk/browse/SASS-3077)

SASS-3077: Update V&C routes in income-tax-submission-frontend

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

[AS] [SASS-2834] implemented dividends gateway navigation

---

app/controllers/testOnly/UserResearchLoginController.scala
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/IVUpliftControllerISpec.scala
it/controllers/StartPageControllerISpec.scala
it/controllers/TaxReturnReceivedControllerISpec.scala
it/controllers/errors/TaxYearErrorControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
it/controllers/predicates/AuthorisedActionSpec.scala
it/controllers/testOnly/UserResearchLoginControllerISpec.scala
it/helpers/WireMockHelper.scala
it/itUtils/IntegrationTest.scala
project/AppDependencies.scala

[SASS-3123](https://jira.tools.tax.service.gov.uk/browse/SASS-3123)

SASS-3123 - Update bootstrap-BE/FE-play-28 dependencies.

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
project/AppDependencies.scala
test/config/MockAppConfig.scala

[SASS-3048] added cannot update employment link

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
project/AppDependencies.scala
test/config/MockAppConfig.scala

Reverts hmrc/income-tax-submission-frontend#250

Revert "[SASS-3048] added cannot update employment link"

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

- []  Have you run the journey tests?

[SASS-2981] charity navigation

---

app/connectors/NrsConnector.scala
app/controllers/AddSectionsToIncomeTaxReturnController.scala
app/controllers/DeclarationPageController.scala
app/services/NrsService.scala
it/connectors/NrsConnectorSpec.scala
test/services/NrsServiceSpec.scala

SASS-2764 Create TailorAddIncomeSources NRS request

---

app/config/AppConfig.scala

include pensions in exludedIncomeSources list

---

conf/application.conf

[SASS-3160](https://jira.tools.tax.service.gov.uk/browse/SASS-3160)

SASS-3160 set as true the local value for managing the error for wrong tax years

---

app/views/OverviewPageView.scala.html
app/views/headerFooterTemplate/Head.scala.html
app/views/headerFooterTemplate/Layout.scala.html

update layout and fix overview item displacement

---

app/controllers/AddSectionsToIncomeTaxReturnController.scala
app/models/IncomeSourcesModel.scala
app/models/OverviewTailoringModel.scala
app/models/statebenefits/AllStateBenefitsData.scala
app/models/statebenefits/CustomerAddedStateBenefit.scala
app/models/statebenefits/CustomerAddedStateBenefitsData.scala
app/models/statebenefits/StateBenefit.scala
app/models/statebenefits/StateBenefitsData.scala
app/utils/JsonUtils.scala
app/views/AddSectionsToIncomeTaxReturnView.scala.html
conf/messages
conf/messages.cy
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/IntegrationTest.scala
project/AppDependencies.scala
run.sh
test/models/OverviewTailoringModelSpec.scala

[SASS-3384](https://jira.tools.tax.service.gov.uk/browse/SASS-3384)

SASS-3384 - Add State Benefits to the Add Section Page.

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/controllers/OverviewPageController.scala
app/services/IncomeSourcesService.scala
app/views/OverviewPageView.scala.html
conf/application.conf
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

[SASS-3372](https://jira.tools.tax.service.gov.uk/browse/SASS-3372)

SASS-3372 - Add State Benefits to the overview page

---

app/config/AppConfig.scala

[SASS-3372](https://jira.tools.tax.service.gov.uk/browse/SASS-3372)

SASS-3372 - Adds state benefits to AppConfig.

---

README.md
app/config/AppConfig.scala
app/controllers/IVUpliftController.scala
app/controllers/predicates/AuthorisedAction.scala
it/controllers/IVUpliftControllerISpec.scala
it/controllers/predicates/AuthorisedActionSpec.scala
it/helpers/WireMockHelper.scala
it/itUtils/IntegrationTest.scala
test/audit/IVHandoffAuditDetailSpec.scala
test/config/MockAppConfig.scala
test/models/userResearch/ResearchUserSpec.scala
test/utils/UnitTest.scala

Increasing the minimum Confidence Level value to 250 rather than 200
https://jira.tools.tax.service.gov.uk/browse/SASS-3946
SASS-3946 Increase the 'Confidence Level' to 250 from 200

SASS-3946 Increase the 'Confidence Level' to 250 from 200

---

app/models/statebenefits/AllStateBenefitsData.scala
it/itUtils/IntegrationTest.scala
test/models/OverviewTailoringModelSpec.scala

[Fix] Api model change.

---

app/controllers/predicates/TaxYearAction.scala
app/repositories/TailoringUserDataRepository.scala
app/views/templates/helpers/NotificationBanner.scala.html

Panel implemented with two h2 elements, one of them is empty
SASS-4093 https://jira.tools.tax.service.gov.uk/browse/SASS-4093

SASS-4093: R7C - Fix Empty tags

---

app/controllers/OverviewPageController.scala
app/models/IncomeSourcesModel.scala
app/views/OverviewPageView.scala.html
it/connectors/IncomeSourcesConnectorSpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
project/AppDependencies.scala
project/plugins.sbt
test/controllers/LanguageSwitchControllerSpec.scala
test/controllers/SignOutControllerSpec.scala
test/models/IncomeSourcesModelSpec.scala
test/models/OverviewTailoringModelSpec.scala
test/models/TaxReturnReceivedModelSpec.scala
test/services/NrsServiceSpec.scala

[SASS-3963](https://jira.tools.tax.service.gov.uk/browse/SASS-3963)

SASS-3963: Allow overview to display when single non fatal error occurs

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
test/config/MockAppConfig.scala

[SASS-3388](https://jira.tools.tax.service.gov.uk/browse/SASS-3388)

[SASS-3388] tailoring employment

---

conf/application.conf

SASS-4536 Enable interest savings

---

app/config/AppConfig.scala
app/controllers/OverviewPageController.scala
app/models/cis/AllCISDeductions.scala
app/models/cis/CISSource.scala
app/views/OverviewPageView.scala.html
test/config/MockAppConfig.scala

update tailoring cis

---

app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala

[SASS-4825](https://jira.tools.tax.service.gov.uk/browse/SASS-4825)

[SASS-4825] update overview page axe issue

---

app/models/pensions/Pensions.scala
it/testModels/PensionsModels.scala

Updated pensions model

---

app/models/pensions/Pensions.scala
app/models/pensions/income/PensionIncome.scala
it/testModels/PensionsModels.scala
test/models/OverviewTailoringModelSpec.scala

[SASS 4685](https://jira.tools.tax.service.gov.uk/browse/SASS-4685)

SASS 4685 - Updated Pension Models to be the same as API

---

app/models/pensions/charges/PensionSchemeUnauthorisedPayments.scala
it/testModels/PensionsModels.scala

SASS 4685 - Frontend build errors

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/controllers/predicates/InYearAction.scala
conf/application.conf
test/config/MockAppConfig.scala

Sass eoy toggle

---

app/views/AddSectionsToIncomeTaxReturnView.scala.html
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala

[SASS-4906](https://jira.tools.tax.service.gov.uk/browse/SASS-4906)

SASS-4906 Accessibility - copy between form controls

---

app/audit/EnterUpdateAndSubmissionServiceAuditDetail.scala
app/connectors/httpParsers/DeclareCrystallisationHttpParser.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/controllers/IVUpliftController.scala
app/controllers/StartPageController.scala
app/controllers/predicates/AuthorisedAction.scala
app/controllers/testOnly/UserResearchLoginController.scala
app/filters/SessionIdFilter.scala
app/repositories/UserDataRepository.scala
app/services/TailoringSessionService.scala
app/utils/TaxYearHelper.scala
app/views/OverviewPageView.scala.html
app/views/headerFooterTemplate/Head.scala.html
app/views/headerFooterTemplate/Layout.scala.html
conf/application.conf
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
project/AppDependencies.scala
test/controllers/predicates/TaxYearActionSpec.scala
test/services/NrsServiceSpec.scala
test/utils/UnitTest.scala

[SASS-4910](https://jira.tools.tax.service.gov.uk/browse/SASS-4910)

SASS-4910 Accessibility Issue - Add sections link Not belong in the list

---

app/views/headerFooterTemplate/Head.scala.html
app/views/templates/helpers/Heading.scala.html
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala
it/controllers/DeclarationPageControllerISpec.scala
it/controllers/StartPageControllerISpec.scala
it/controllers/errors/AddressHasChangedPageControllerISpec.scala
it/controllers/errors/BusinessValidationRulesControllerISpec.scala
it/controllers/errors/NoUpdatesProvidedPageControllerISpec.scala
it/controllers/errors/NoValidIncomeSourcesISpec.scala
it/controllers/errors/ReturnTaxYearExistsControllerISpec.scala
it/controllers/errors/TaxReturnPreviouslyUpdatedControllerISpec.scala
it/controllers/errors/UnauthorisedUserErrorControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
it/itUtils/ViewHelpers.scala
it/itUtils/ViewTest.scala
it/services/TailoringSessionServiceISpec.scala
it/views/helpers/HeadingISpec.scala

[SASS-4899](https://jira.tools.tax.service.gov.uk/browse/SASS-4899)

SASS-4899 Accessibility issue fix -Captions provided inconsistently

---

conf/messages.cy

[SASS-4962] https://jira.tools.tax.service.gov.uk/browse/SASS-4962

SASS-4962 Amend welsh content

---

conf/application.conf

enable gains for accessibility

---

conf/application.conf

This reverts commit 5325cc6e4daa1196b74137ea9ddc07a58a0bde2a.

Revert "enable gains for accessibility"

---

conf/application.conf

SASS-5055 Add feature switch functionality to Additional information

---

app/common/IncomeSources.scala
app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/controllers/AddSectionsToIncomeTaxReturnController.scala
app/controllers/OverviewPageController.scala
app/forms/AddSectionsForm.scala
app/models/IncomeSourcesModel.scala
app/models/OverviewTailoringModel.scala
app/models/SelfEmploymentData.scala
app/views/AddSectionsToIncomeTaxReturnView.scala.html
app/views/OverviewPageView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
it/controllers/AddSectionsToIncomeTaxReturnControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
it/itUtils/IntegrationTest.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala
test/models/OverviewTailoringModelSpec.scala

Add 'Self-Employment' as a tailoring option with a checkbox in journey which then displays a Self Employment link on the overview page.
[SASS-5549](https://jira.tools.tax.service.gov.uk/browse/SASS-5549)

[SASS-5549] Add Self-employment checkbox to Submission task list

---

app/config/AppConfig.scala
app/views/OverviewPageView.scala.html
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

[SASS-5276] Add taxYear to Self-Employment URL

---

app/views/OverviewPageView.scala.html
app/views/templates/helpers/NotificationBanner.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
conf/prod.routes
it/controllers/overviewPage/OverviewPageControllerISpec.scala
it/itUtils/OverviewPageHelpers.scala
it/itUtils/ViewTest.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

SASS-6664 Gains update summary page behaviour to include prior data

---

app/connectors/IncomeSourcesConnector.scala
app/connectors/httpParsers/APIParser.scala
app/connectors/httpParsers/IncomeSourcesHttpParser.scala
app/controllers/OverviewPageController.scala
app/controllers/predicates/AuthorisedAction.scala
it/connectors/IncomeSourcesConnectorSpec.scala

Improve logging in submission frontend.

Add logging

---

conf/application-json-logger.xml
conf/logback.xml

Add warning log level to application-json-logger.xml

Add WARN logger

---

app/connectors/httpParsers/APIParser.scala
app/models/gains/InsurancePoliciesModel.scala
it/itUtils/IntegrationTest.scala
test/models/OverviewTailoringModelSpec.scala

Update insurance policies model, rm log that was repeated.

SASS: Update insurance policies model, rm log that was repeated

---

app/models/IncomeSourcesModel.scala

Update IncomeSourcesModel so the errors property can handle a list of errors.

SASS-7323: Update IncomeSourcesModel to stop parsing errors

---

project/AppDependencies.scala

SASS-7337 Updated play frontend library version for tudor crown change

---

app/controllers/AddSectionsToIncomeTaxReturnController.scala

Remove Notable Event-Tailor Add Income Sources.
SASS-7297

SASS-7297: Remove Notable Event-Tailor Add Income Sources

---

app/views/OverviewPageView.scala.html
conf/application.conf
it/test/controllers/IVUpliftControllerISpec.scala
it/test/controllers/overviewPage/OverviewPageControllerISpec.scala
it/test/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala
it/test/itUtils/OverviewPageHelpers.scala
project/plugins.sbt

SASS-7869 Fix overview page status and cya redirection for dividends

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/controllers/OverviewPageController.scala
app/controllers/SessionExpiredController.scala
app/controllers/StartPageController.scala
app/controllers/TaxYearErrorController.scala
app/controllers/UnauthorisedUserErrorController.scala
app/controllers/errors/AgentAuthErrorController.scala
app/controllers/errors/IndividualAuthErrorController.scala
app/controllers/errors/YouNeedAgentServicesController.scala
app/controllers/predicates/AuthorisedAction.scala
conf/application.conf
it/test/controllers/StartPageControllerISpec.scala
it/test/itUtils/IntegrationTest.scala
test/config/MockAppConfig.scala

SASS-8048 new tailoring feature switch for common task list

---

app/assets/stylesheets/application.scss
app/views/OverviewPageView.scala.html
app/views/headerFooterTemplate/Head.scala.html
app/views/headerFooterTemplate/Layout.scala.html
conf/messages
conf/messages.cy
project/AppDependencies.scala

SASS-8193 play frontend upgrade

---

README.md
app/controllers/OverviewPageController.scala
app/models/ForeignInterestModel.scala
app/models/StockDividendsModel.scala
app/views/OverviewPageView.scala.html
project/AppDependencies.scala
test/models/StockDividendsModelSpec.scala

To enable Dividends to reflect on Excluded status when required
Linked to SASS-8028

SASS-8051: Updated Dividends journey to display Excluded status when required

---

app/controllers/OverviewPageController.scala

Fixed QA issue with exclude and update status not reflecting if stock dividend was present

fixed qa issue for 8028

---

conf/messages
conf/messages.cy
it/test/config/MessagesSpec.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

Added messages for the task list

SASS-8325: Add messages for the task list

---

app/connectors/LiabilityCalculationConnector.scala
app/controllers/OverviewPageController.scala
app/services/LiabilityCalculationService.scala
it/test/connectors/LiabilityCalculationConnectorSpec.scala
it/test/controllers/overviewPage/OverviewPageControllerISpec.scala
it/test/itUtils/OverviewPageHelpers.scala
test/services/LiabilityCalculationServiceSpec.scala

Fix in year estimate not sending request for calculation.

SASS-8359: fix in year estimate calc

---

conf/logback.xml
conf/messages
conf/messages.cy

SASS-8366: Add an additional Option to the Payment Into Pensions Page

---

conf/messages.cy
it/test/config/MessagesSpec.scala

SASS-8673: Welsh Translations for Common Task list

---

conf/messages
it/test/controllers/overviewPage/OverviewPageControllerISpec.scala
it/test/controllers/overviewPage/OverviewPageControllerTailoringISpec.scala

SASS-7913 | Change Not started to Not Yet Started

---

conf/messages

Main ticket: [SASS-7915](https://jira.tools.tax.service.gov.uk/browse/SASS-7915)

SASS-9977: Updating status message to check

---

app/controllers/OverviewPageController.scala
it/test/controllers/overviewPage/OverviewPageControllerISpec.scala

Spike, so no main or Jira ticket available for this to track.

Updating overview page controller to return to common task list when future switch is enabled

---

conf/messages.cy

SASS-9977: updating welsh message for checknow

---

conf/messages.cy

SASS-9977: Updating Not yet Started value of welsh

---

app/config/AppConfig.scala
app/controllers/TaskListPageController.scala
it/test/controllers/TaskListPageControllerISpec.scala
it/test/itUtils/IntegrationTest.scala
it/test/itUtils/OverviewPageHelpers.scala
test/config/MockAppConfig.scala

Main Ticket: [SASS-10057](https://jira.tools.tax.service.gov.uk/browse/SASS-10057)

SASS-10064 | Redirect the user to Add sections Screen, if there is no tailoring tasklist data 

---

app/config/ErrorHandler.scala
app/views/headerFooterTemplate/Layout.scala.html
build.sbt
conf/application.conf
it/test/controllers/StartPageControllerISpec.scala
it/test/controllers/overviewPage/OverviewPageControllerISpec.scala
project/AppDependencies.scala
project/plugins.sbt

Fix console errors in browser.
Update dependencies some selector changes in spec due to the updates.

SASS-10230: Fix console errors in browser, update dependencies

---

app/viewmodels/TaskListPageViewModel.scala
check.sh

SASS-10468 Update CSS class for In Progress

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
conf/application.conf
it/test/itUtils/IntegrationTest.scala
project/plugins.sbt
test/utils/AesGcmAdCryptoSpec.scala

Added as requested here - https://github.com/hmrc/app-config-qa/pull/24190

SASS-10720 Added feature-switch flag to taxYearErrorFeatureSwitch and alwaysEOY

---

conf/messages.cy
project/AppDependencies.scala
project/plugins.sbt

SASS-11069: Added welsh content

---

app/views/TaskListPageView.scala.html

SASS-11066 - change button colour

---

conf/messages.cy
it/test/controllers/errors/SupportingAgentAuthErrorControllerISpec.scala
project/plugins.sbt

SASS-11161: EMA Welsh changes

---

conf/application.conf

SASS-11542: Common task list endpoint
